### ISSUE TITLE
Uncaught TypeError: _this.encryptBuffer is not a function

### ISSUE THREAD

**Issue by vlstefanovic** [MattFlower/organized#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Debian GNU/Linux
**Thrown From**: [organized](https://github.com/MattFlower/organized) package 0.6.6

### Stack Trace

Uncaught TypeError: _this.encryptBuffer is not a function

```
At /home/vstefanovic/.atom/packages/organized/lib/organized.coffee:118

TypeError: _this.encryptBuffer is not a function
    at /packages/organized/lib/organized.coffee:118:103)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:301:20)
    at SelectListView.didClickItem (/app.asar/node_modules/atom-select-list/src/select-list-view.js:220:10)
    at ListItemView.onclick (/app.asar/node_modules/atom-select-list/src/select-list-view.js:156:33)
    at ListItemView.didClick (/app.asar/node_modules/atom-select-list/src/select-list-view.js:349:10)
```

### Commands

```
     -0:10.2.0 command-palette:toggle (input.hidden-input)
     -0:02.0 organized:encryptBuffer (input.hidden-input)
```

### Non-Core Packages

```
nuclide undefined 
organized 0.6.6 
```

**Comment by MattFlower** [comment]
Hi @vlstefanovic, at this point encryption of buffers is not yet supported.  I'll remove the keymap in the next build so there won't be any more confusion.
