### ISSUE TITLE
Failed to activate the organized package

### ISSUE THREAD

**Issue by nlfiedler** [MattFlower/organized#27]
Updated to the latest version as of today, restarted Atom per request, got the error below.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [organized](https://github.com/MattFlower/organized) package 0.8.0

### Stack Trace

Failed to activate the organized package

```
At Cannot read property 'getGrammar' of undefined

TypeError: Cannot read property 'getGrammar' of undefined
    at _findInDirectories (/packages/organized/lib/sidebar-items.coffee:97:36)
    at findInDirectories (/packages/organized/lib/sidebar-items.coffee:60:3)
    at SidebarView.module.exports.SidebarView.populateSidebarItems (/packages/organized/lib/sidebar-view.coffee:166:9)
    at SidebarView.module.exports.SidebarView.refreshAll (/packages/organized/lib/sidebar-view.coffee:125:6)
    at SidebarView.module.exports.SidebarView.activate (/packages/organized/lib/sidebar-view.coffee:80:8)
    at Object.activate (/packages/organized/lib/organized.coffee:169:14)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-docker 1.1.8 
language-elixir 0.20.3 
language-elm 1.5.0 
language-erlang 3.2.0 
language-rust 0.4.12 
lines 0.13.1 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-elm-make 0.26.2 
linter-erlang 0.4.0 
linter-js-standard 4.0.2 
linter-jshint 3.1.6 
linter-python 3.1.2 
linter-rust 0.8.0 
linter-toml 0.1.1 
linter-ui-default 1.6.10 
organized 0.8.0 
project-manager 3.3.5 
standard-formatter 2.8.0 
standardjs-snippets 2.6.2 
```

**Comment by MattFlower** [comment]
0.8.1 has a fix and has been released, please let me know if you still see the problem.
