### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by ramana106** [MattFlower/organized#28]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 14.04.5
**Thrown From**: [organized](https://github.com/MattFlower/organized) package 0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /home/ramanathan/.atom/packages/organized/lib/sidebar-items.coffee:97

TypeError: Cannot read property 'getGrammar' of undefined
    at _findInDirectories (/packages/organized/lib/sidebar-items.coffee:97:36)
    at findInDirectories (/packages/organized/lib/sidebar-items.coffee:60:3)
    at SidebarView.module.exports.SidebarView.populateSidebarItems (/packages/organized/lib/sidebar-view.coffee:166:9)
    at SidebarView.module.exports.SidebarView.refreshAll (/packages/organized/lib/sidebar-view.coffee:125:6)
    at /packages/organized/lib/sidebar-view.coffee:62:12
    at /usr/share/atom/resources/app/src/config.js:676:22
    at /usr/share/atom/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:248:20)
    at SettingsPanel.set (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:315:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1694:26)
    at later (/usr/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -5:51.5.0 intentions:highlight (input.hidden-input)
     -5:51.2.0 settings-view:open (input.hidden-input)
     -5:32.2.0 core:backspace (input.hidden-input)
     -5:31 intentions:highlight (input.hidden-input)
  3x -5:26.5.0 core:backspace (input.hidden-input)
  2x -5:18.1.0 organized:newStarLine (input.hidden-input)
  7x -5:17.5.0 core:backspace (input.hidden-input)
     -5:11 intentions:highlight (input.hidden-input)
     -5:10 settings-view:open (input.hidden-input)
  6x -4:30.8.0 intentions:highlight (input.hidden-input)
  2x -1:14.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:59.2.0 encoding-selector:show (atom-text-editor.editor)
     -0:57.3.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
  3x -0:33.3.0 core:backspace (input.hidden-input)
     -0:28.6.0 intentions:highlight (input.hidden-input)
     -0:27.7.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
aurora-theme 1.2.2 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
colorblind-wombat-dark-syntax 0.6.0 
git-difftool 0.2.7 
git-plus 7.10.0 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-python 3.1.2 
linter-ui-default 1.6.10 
MagicPython 1.0.12 
markdown-preview-plus 2.4.16 
minimap 4.29.7 
multi-cursor 2.1.5 
organized 0.8.0 
platformio-ide-terminal 2.7.0 
python-tools 0.6.9 
split-diff 1.5.1 
tool-bar 1.1.0 
you-complete-me 0.8.0 
```

**Comment by MattFlower** [comment]
Thanks Ramana, I have a fix that will be going out as 0.8.1.  I'm finishing up some unit tests, so it will probably be tonight or tomorrow before it goes out.

**Comment by MattFlower** [comment]
0.8.1 has a fix and has been released, please let me know if you still see the problem.

**Comment by ramana106** [comment]
Sure.. thank you..
