### ISSUE TITLE
Regex "Invalid group" causing command failures

### ISSUE THREAD

**Issue by jkamenik** [MattFlower/organized#5]
Almost every command I have tried fails with an "invalid group" error similar to the below.

OS: Mac 10.11.6
Atom: 1.12.3
organized: 0.5.1

```
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871
Hide Stack Trace
SyntaxError: Invalid regular expression: /(?<=^\s*)([\*\-\+]|\d+\.)/: Invalid group
    at Star._starIndexOf (/Users/jkamenik/.atom/packages/organized/lib/star.coffee:132:5)
    at Star._processStar (/Users/jkamenik/.atom/packages/organized/lib/star.coffee:48:17)
    at new Star (/Users/jkamenik/.atom/packages/organized/lib/star.coffee:29:6)
    at Object._starInfo (/Users/jkamenik/.atom/packages/organized/lib/organized.coffee:630:16)
    at /Users/jkamenik/.atom/packages/organized/lib/organized.coffee:214:22
    at /Users/jkamenik/.atom/packages/organized/lib/organized.coffee:658:11
    at Object._withAllSelectedLines (/Users/jkamenik/.atom/packages/organized/lib/organized.coffee:649:9)
    at /Users/jkamenik/.atom/packages/organized/lib/organized.coffee:210:10
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1524:26)
    at Object.indent (/Users/jkamenik/.atom/packages/organized/lib/organized.coffee:209:14)
    at atom-text-editor.subscriptions.add.atom.commands.add.organized:indent (/Users/jkamenik/.atom/packages/organized/lib/organized.coffee:95:96)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

or 

```
/Users/jkamenik/.atom/packages/organized/lib/star.coffee:132
Hide Stack Trace
SyntaxError: Invalid regular expression: /(?<=^\s*)([\*\-\+]|\d+\.)/: Invalid group
    at Star._starIndexOf (/Users/jkamenik/.atom/packages/organized/lib/star.coffee:132:5)
    at Star._processStar (/Users/jkamenik/.atom/packages/organized/lib/star.coffee:48:17)
    at new Star (/Users/jkamenik/.atom/packages/organized/lib/star.coffee:29:6)
    at Object._starInfo (/Users/jkamenik/.atom/packages/organized/lib/organized.coffee:630:16)
    at Object.newStarLine (/Users/jkamenik/.atom/packages/organized/lib/organized.coffee:314:15)
    at atom-text-editor.subscriptions.add.atom.commands.add.organized:newStarLine (/Users/jkamenik/.atom/packages/organized/lib/organized.coffee:101:101)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by jkamenik** [comment]
From https://regex101.com/ it appears that the issue is the '*' in the '(?<=^\s*)' part.  This makes the look behind non-fixed and invalid.
